// all this data is generated by the api using Postman
// this data is for demonstration and as example only
// The Rekonition will return this reponse to us when we upload the image 

var rsp1 = {
	"Results" : {
		"Labels" : [ {
			"Confidence" : 99.06697082519531,
			"Name" : "Person"
		}, {
			"Confidence" : 99.06697082519531,
			"Name" : "Human"
		}, {
			"Confidence" : 92.77681732177734,
			"Name" : "Canopy"
		}, {
			"Confidence" : 92.77681732177734,
			"Name" : "Umbrella"
		}, {
			"Confidence" : 84.23519134521484,
			"Name" : "Tent"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Shelter"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Rural"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Nature"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Countryside"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Outdoors"
		}, {
			"Confidence" : 76.30335998535156,
			"Name" : "Building"
		}, {
			"Confidence" : 72.34380340576172,
			"Name" : "Vehicle"
		}, {
			"Confidence" : 72.34380340576172,
			"Name" : "Bicycle"
		}, {
			"Confidence" : 72.34380340576172,
			"Name" : "Transportation"
		}, {
			"Confidence" : 72.34380340576172,
			"Name" : "Bike"
		} ]
	},
	"Filename" : "43b5afc623cf35509c6e35d0e16791af.jpg"
};

var rsp2 = {
	"Results" : {
		"Labels" : [ {
			"Confidence" : 97.8507080078125,
			"Name" : "Kitten"
		}, {
			"Confidence" : 97.8507080078125,
			"Name" : "Mammal"
		}, {
			"Confidence" : 97.8507080078125,
			"Name" : "Animal"
		}, {
			"Confidence" : 97.8507080078125,
			"Name" : "Cat"
		}, {
			"Confidence" : 97.8507080078125,
			"Name" : "Pet"
		}, {
			"Confidence" : 93.79776763916016,
			"Name" : "Manx"
		} ]
	},
	"Filename" : "8b515ef430e20fc490535c62f2642947.jpg"
};
var rsp3 = {
	"Results" : {
		"Labels" : [ {
			"Confidence" : 99.44891357421875,
			"Name" : "Human"
		}, {
			"Confidence" : 99.44891357421875,
			"Name" : "Person"
		}, {
			"Confidence" : 97.90007781982422,
			"Name" : "Vehicle"
		}, {
			"Confidence" : 97.90007781982422,
			"Name" : "Transportation"
		}, {
			"Confidence" : 97.90007781982422,
			"Name" : "Train"
		}, {
			"Confidence" : 97.54658508300781,
			"Name" : "Terminal"
		}, {
			"Confidence" : 97.54658508300781,
			"Name" : "Train Station"
		}, {
			"Confidence" : 84.88362121582031,
			"Name" : "Tarmac"
		}, {
			"Confidence" : 84.88362121582031,
			"Name" : "Asphalt"
		}, {
			"Confidence" : 83.65003204345703,
			"Name" : "Handrail"
		}, {
			"Confidence" : 83.65003204345703,
			"Name" : "Banister"
		}, {
			"Confidence" : 80.32102966308594,
			"Name" : "Overcoat"
		}, {
			"Confidence" : 80.32102966308594,
			"Name" : "Clothing"
		}, {
			"Confidence" : 80.32102966308594,
			"Name" : "Coat"
		}, {
			"Confidence" : 80.32102966308594,
			"Name" : "Apparel"
		}, {
			"Confidence" : 73.33248138427734,
			"Name" : "Subway"
		} ]
	},
	"Filename" : "35db653e64c0d98b1645c2c427ca4d73.jpg"
};